language: go
go:
  -1.7.x
  -1.8.x
sudo: false
install:
  - GLIDE_VERSION=V0.12.3
  - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
  - curl -l $GLIDE_DOWNLOAD | tar -xvz
  - export PATH=$PATH:$PWD/linux-amd64/
  - glide install
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./clean.sh
