language: go
go:
  - 1.7.x
  - 1.8.x
before_install:



install:
  - git clone https://github.com/bitcoin-core/secp256k1.git /tmp/secp256k1
  - pushd /tmp/secp256k1
  - ./autogen.sh
  - ./configure --enable-experimental --enable-module-ecdh --enable-module-recovery
  - make -j4
  - sudo make install
  - cd -
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - glide install
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./check.sh