language: go
go:
  - 1.7.x
  - 1.8.x
sudo: false
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - glide install
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./check.sh
addons:
  ssh_known_hosts:
  - github.com
  - ssh.github.com